### ISSUE TITLE
Can't docker pull govcms8-saas "cli" image - access denied

### ISSUE THREAD

**Issue by joshua-graham-adelphi** [govCMS/govcms8-scaffold#19]
See below error:

> $ docker-compose pull
> Pulling cli     ... error
> Pulling test    ... done
> Pulling nginx   ... done
> Pulling php     ... done
> Pulling mariadb ... done
> Pulling chrome  ... done
> 
> ERROR: for cli  pull access denied for govcms8-saas, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
> ERROR: pull access denied for govcms8-saas, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

Have to resort to "re-using" test as "cli" image for now.

> diff --git a/docker-compose.yml b/docker-compose.yml
> index 3f19e39..5a3deea 100644
> --- a/docker-compose.yml
> +++ b/docker-compose.yml
> @@ -30,7 +30,8 @@ services:
>      build:
>        context: .
>        dockerfile: .docker/Dockerfile.cli
> -    image: *lagoon-project
> +    #image: *lagoon-project
> +    image: govcms8lagoon/test
>      labels:
>        lagoon.type: cli-persistent
>        lagoon.persistent.name: nginx

**Comment by fubarhouse** [comment]
@joshua-graham-adelphi,

I'm also getting this, but it's important to note that the cli image doesn't exist anywhere other than the `localhost`. So in order to fix this, you can pull the base image and rebuild the cli image.

You should also note that the `ahoy pull` command which is recommended also uses this method, and it executes the following. It may be a little confusing because it uses a templating engine to target fields, but it essentially pulls all image with references containing the substring `govcms8lagoon/`.
```
docker image ls --format \"{{.Repository}}:{{.Tag}}\" | grep govcms8lagoon/ | grep -v none | xargs -n1 docker pull | cat
```

To pull the base image directly and rebuild the `cli` image, you can do the following:
1. `docker pull govcms8lagoon/govcms8` (alternatively `govcmslagoon/govcms7` for GovCMS7)
2. `docker-compose build cli`

FWIW `cli` is the inherited value of the service name in the `docker-compose.yml` file and refers to a Dockerfile with the same name. The container name itself does get inherited from the value of the service name present in the `docker-compose.yml` file.

If you're still running into issues, please refer to the `.ahoy.yml` command file, because that is what is officially supported and recommended for ease of use.

**Comment by joshua-graham-adelphi** [comment]
Ah i see, I've updated by suggested "docker pull doco" PR, since I'm mainly using windows.

https://github.com/govCMS/govcms8-scaffold/issues/19
